# Generated by Django 3.2.4 on 2021-06-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='memorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(default='', max_length=30, null=True)),
                ('precio', models.IntegerField(default='', null=True)),
                ('marca', models.CharField(default='', max_length=30, null=True)),
                ('modelo', models.CharField(default='', max_length=30, null=True)),
                ('fecha', models.CharField(default='', max_length=20, null=True)),
                ('imagen', models.ImageField(null='True', upload_to='imagen')),
            ],
        ),
        migrations.CreateModel(
            name='monitores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(default='', max_length=30, null=True)),
                ('precio', models.IntegerField(default='', null=True)),
                ('marca', models.CharField(default='', max_length=30, null=True)),
                ('modelo', models.CharField(default='', max_length=30, null=True)),
                ('fecha', models.CharField(default='', max_length=20, null=True)),
                ('imagen', models.ImageField(null='True', upload_to='imagen')),
            ],
        ),
        migrations.CreateModel(
            name='teclados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(default='', max_length=30, null=True)),
                ('precio', models.IntegerField(default='', null=True)),
                ('marca', models.CharField(default='', max_length=30, null=True)),
                ('modelo', models.CharField(default='', max_length=30, null=True)),
                ('fecha', models.CharField(default='', max_length=20, null=True)),
                ('imagen', models.ImageField(null='True', upload_to='imagen')),
            ],
        ),
    ]
